behaviors:
  3v3_Soccer_Goalie:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960 
      learning_rate: 0.0001
      beta: 0.01
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 2048
    summary_freq: 10000
    threaded: false
    self_play:
      save_steps: 50000
      team_change: 100000
      swap_steps: 10000
      window: 50
      play_against_latest_model_ratio: 0.3
      initial_elo: 1200.0
  3v3_Soccer_Strike:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960 
      learning_rate: 0.0001
      beta: 0.01
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 2048
    summary_freq: 10000
    threaded: false
    self_play:
      save_steps: 50000
      team_change: 100000
      swap_steps: 10000
      window: 50
      play_against_latest_model_ratio: 0.3
      initial_elo: 1200.0
